---
name: geodash-plugin-main
controllers:
  - name: GeoDashControllerMain
    path: GeoDashControllerMain.js
    handlers:
      - { event: clickedOnMap, handler: clickedOnMap }
      - { event: filterChanged, handler: filterChanged }
      - { event: hideLayer, handler: hideLayer }
      - { event: hideLayers, handler: hideLayers }
      - { event: hideModal, handler: hideModal }
      - { event: layerLoaded, handler: layerLoaded }
      - { event: requestToggleComponent, handler: requestToggleComponent }
      - { event: selectStyle, handler: selectStyle }
      - { event: showLayer, handler: showLayer }
      - { event: showLayers, handler: showLayers }
      - { event: showModal, handler: showModal }
      - { event: stateChanged, handler: stateChanged }
      - { event: switchBaseLayer, handler: switchBaseLayer }
      - { event: viewChanged, handler: viewChanged }
      - { event: zoomIn, handler: zoomIn }
      - { event: zoomOut, handler: zoomOut }
      - { event: zoomToLayer, handler: zoomToLayer }
      - { event: zoomToLocation, handler: zoomToLocation }
      - { event: flyToLocation, handler: flyToLocation }
      - { event: flyToCurrentLocation, handler: flyToCurrentLocation }
      - { event: flyToExtent, handler: flyToExtent }
      - { event: printMap, handler: printMap }
      - { event: toggleFullScreen, handler: toggleFullScreen }
      - { event: toggleFeatureLayer, handler: toggleFeatureLayer }
      - { event: toggleControl, handler: toggleControl }
      - { event: startGeolocation, handler: startGeolocation }
      - { event: stopGeolocation, handler: stopGeolocation }
      - { event: toggleGeolocation, handler: toggleGeolocation }
directives:
  - geodashMain.js
  - geodashMap.js
templates:
  - main.tpl.html
handlers: []
